version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: allo-backend-deploy-staging
    ports:
      - "5000:4000"
    env_file:
      - /etc/allo/server/.env.staging
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
    networks:
      - allo-network

  website:
    build:
      context: ./websites/main
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_BASE: ${NEXT_PUBLIC_PROXY_BASE}
        NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER}
    container_name: allo-website-deploy-staging
    ports:
      - "5001:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
    networks:
      - allo-network

  admin:
    build:
      context: ./websites/admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_BASE: ${NEXT_PUBLIC_PROXY_BASE}
        NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER}
        DATABASE_URI: ${DATABASE_URI}
        SERVICE_KEY: ${SERVICE_KEY}
    container_name: allo-admin-deploy-staging
    ports:
      - "5002:3000"
    env_file:
      - /etc/allo/websites/admin/.env.staging
    restart: unless-stopped
    environment:
      - NODE_ENV=staging
    networks:
      - allo-network

networks:
  allo-network:
    driver: bridge
