version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: allo-backend
    ports:
      - "1234:4000"
    env_file:
      - /etc/allo/server/.env.development
    restart: unless-stopped
    networks:
      - allo-network

  website:
    build:
      context: ./websites/main
      dockerfile: Dockerfile
      args:
        ENV_FILE: /etc/allo/websites/main/.env.development
    container_name: allo-website
    ports:
      - "3000:3000"
    env_file:
      - /etc/allo/websites/main/.env.development
    restart: unless-stopped
    networks:
      - allo-network

  admin:
    build:
      context: ./websites/admin
      dockerfile: Dockerfile
      args:
        ENV_FILE: /etc/allo/websites/admin/.env.development
    container_name: allo-admin
    ports:
      - "3001:3000"
    env_file:
      - /etc/allo/websites/admin/.env.development
    restart: unless-stopped
    networks:
      - allo-network

networks:
  allo-network:
    driver: bridge
