version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: allo-backend-deploy-production
    ports:
      - "4000:4000"
    env_file:
      - /etc/allo/server/.env.production
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - allo-network

  website:
    build:
      context: ./websites/main
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_BASE: ${NEXT_PUBLIC_PROXY_BASE}
        NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER}
    container_name: allo-website-deploy-production
    ports:
      - "3000:3000"
    env_file:
      - /etc/allo/websites/main/.env.production
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - allo-network

  admin:
    build:
      context: ./websites/admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PROXY_BASE: ${NEXT_PUBLIC_PROXY_BASE}
        NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER}
    container_name: allo-admin-deploy-production
    ports:
      - "3001:3000"
    env_file:
      - /etc/allo/websites/admin/.env.production
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - allo-network

networks:
  allo-network:
    driver: bridge
